name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "gh-pages"
  cancel-in-progress: true

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bump build number
        if: ${{ !contains(github.event.head_commit.message, '[build-skip]') }}
        run: |
          set -e
          FILE=build-number.json
          if [ -f "$FILE" ]; then
            CURRENT=$(jq -r '.build // 0' "$FILE")
          else
            CURRENT=0
          fi
          NEXT=$((CURRENT+1))
          echo "{\"build\": $NEXT}" > "$FILE"
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add "$FILE"
          git commit -m "chore: bump build number to $NEXT [build-skip]" || echo "No build number change"
          git push
          echo "Build number bumped to $NEXT; triggering new run and exiting early.";
          exit 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --run

      - name: Build
        env:
          VITE_BASE: /${{ github.event.repository.name }}/
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4